version: 2

updates:
  # Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "kbrockhoff"
    assignees:
      - "kbrockhoff"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    # Group minor and patch updates
    groups:
      terraform-plugin:
        patterns:
          - "github.com/hashicorp/terraform-plugin-*"
      testing:
        patterns:
          - "github.com/stretchr/testify"
          - "github.com/golangci/golangci-lint"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "kbrockhoff"
    assignees:
      - "kbrockhoff"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "*"