run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters
    - asciicheck
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck

  disable:
    - deadcode      # deprecated
    - exhaustivestruct # deprecated
    - golint        # deprecated
    - ifshort       # deprecated
    - interfacer    # deprecated
    - maligned      # deprecated
    - nosnakecase   # deprecated
    - scopelint     # deprecated
    - structcheck   # deprecated
    - varcheck      # deprecated

linters-settings:
  cyclop:
    max-complexity: 15
  
  dupl:
    threshold: 120
  
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Debug)
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Info)
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Warn)
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Error)
  
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  
  forbidigo:
    forbid:
      - 'fmt\.Print.*'
      - 'log\.Print.*'
      - 'panic'
    exclude-godoc-examples: true
  
  funlen:
    lines: 100
    statements: 60
  
  gocognit:
    min-complexity: 20
  
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: true
  
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
      - BUG
      - FIXME
  
  gofmt:
    simplify: true
  
  gofumpt:
    extra-rules: true
  
  goimports:
    local-prefixes: github.com/kbrockhoff/terraform-provider-context
  
  gomnd:
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '8'
      - '10'
      - '24'
      - '60'
      - '256'
      - '1000'
      - '1024'
    ignored-functions:
      - 'args'
      - 'strconv.FormatFloat'
      - 'strconv.FormatInt'
      - 'strconv.FormatUint'
      - 'strconv.ParseFloat'
      - 'strconv.ParseInt'
      - 'strconv.ParseUint'
    ignored-files:
      - 'test/*.go'
      - '*_test.go'
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this project
  
  grouper:
    const-require-single-const: false
    var-require-single-var: false
  
  lll:
    line-length: 120
    tab-width: 4
  
  maintidx:
    threshold: 20
  
  misspell:
    locale: US
    ignore-words:
      - colour
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 5
  
  nlreturn:
    block-size: 5
  
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: true
    require-specific: true
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  predeclared:
    ignore: ""
    q: false
  
  revive:
    severity: warning
    rules:
      - name: atomic
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: confusing-naming
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: range-val-in-closure
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: useless-break
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value
  
  stylecheck:
    checks: ["all"]
  
  tenv:
    all: true
  
  thelper:
    test:
      first: true
      name: true
      begin: true
    benchmark:
      first: true
      name: true
      begin: true
    tb:
      first: true
      name: true
      begin: true
  
  unparam:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false
  
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - maintidx
        - wrapcheck
        - nlreturn
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines with go:generate or //go:
    - linters:
        - lll
      source: "^//go:"
    
    # Exclude godox for TODO comments in examples
    - path: examples/
      linters:
        - godox
    
    # Disable some linters for auto-generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    
    # Allow fmt.Print* in main.go for CLI output
    - path: main\.go
      linters:
        - forbidigo
      text: "fmt\\.Print"
    
    # Allow long lines in generated files and test data
    - path: "(.*_gen\\.go|testdata/.*)"
      linters:
        - lll
  
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false