name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand and evaluate your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have read the provider documentation and examples
          required: true
        - label: This feature is not already available in the current version
          required: true

  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What is the current limitation?
      placeholder: |
        Describe the problem or limitation you're facing...
        
        For example:
        - It's difficult to...
        - Users need to...
        - Currently, there's no way to...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        Describe your proposed solution in detail...
        
        For example:
        - Add a new configuration option...
        - Implement support for...
        - Extend the provider to...
    validations:
      required: true

  - type: dropdown
    id: feature_category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Provider Configuration
        - Data Source Configuration
        - Naming Logic
        - Tag Processing
        - Cloud Provider Support
        - Validation
        - Output Formats
        - Git Integration
        - Documentation
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: cloud_providers
    attributes:
      label: Affected Cloud Providers
      description: Which cloud providers would this feature affect?
      multiple: true
      options:
        - AWS
        - Azure
        - GCP
        - All cloud providers
        - Provider-agnostic
        - Default/DC only
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be beneficial
      placeholder: |
        1. Use case 1: When a user wants to...
        2. Use case 2: In environments where...
        3. Use case 3: For organizations that need...
    validations:
      required: true

  - type: textarea
    id: example_configuration
    attributes:
      label: Example Configuration
      description: Show how this feature would be used in Terraform configuration
      render: hcl
      placeholder: |
        provider "brockhoff" {
          # New provider configuration options
        }

        data "brockhoff_context" "example" {
          # New data source attributes
          new_feature_option = "value"
        }

        # Example of how outputs would be used
        resource "aws_instance" "example" {
          tags = data.brockhoff_context.example.tags
        }

  - type: textarea
    id: expected_outputs
    attributes:
      label: Expected Behavior/Outputs
      description: What should the feature produce or how should it behave?
      placeholder: |
        Describe the expected behavior, outputs, or results...
        
        For example:
        - The feature should generate...
        - Users should be able to...
        - The output should include...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? Why is this the preferred approach?
      placeholder: |
        Describe alternative solutions you've considered...
        
        For example:
        - Alternative 1: Using external data sources...
        - Alternative 2: Manual configuration...
        - Alternative 3: Different provider approach...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have - Would be helpful but not critical
        - Important - Would significantly improve my workflow
        - High - Blocking or severely impacting my use case
        - Critical - Cannot use provider effectively without this
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple configuration change or minor logic update
        - Medium - New functionality but follows existing patterns
        - High - Significant new feature requiring design changes
        - Unknown - Not sure about implementation complexity

  - type: textarea
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes to the current API?
      placeholder: |
        Consider:
        - Would existing configurations still work?
        - Are new required fields being added?
        - Would output formats change?
        - Would validation rules change?

  - type: textarea
    id: migration_path
    attributes:
      label: Migration Path
      description: If breaking changes are needed, what migration path would you suggest?
      placeholder: |
        For example:
        - Deprecate old options in v2.x
        - Provide compatibility layer for...
        - Auto-migration script for...

  - type: textarea
    id: testing_approach
    attributes:
      label: Testing Considerations
      description: How should this feature be tested?
      placeholder: |
        Consider:
        - Unit tests for new logic
        - Integration tests with specific cloud providers  
        - Example configurations to validate
        - Edge cases to test

  - type: textarea
    id: documentation_needs
    attributes:
      label: Documentation Requirements
      description: What documentation would be needed for this feature?
      placeholder: |
        For example:
        - Update provider documentation
        - New examples demonstrating usage
        - Migration guide (if breaking changes)
        - Blog post or announcement

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, links, or information that might be helpful
      placeholder: |
        Any additional information that might help us understand the request...
        
        For example:
        - Links to related issues or discussions
        - References to similar features in other providers
        - Screenshots or diagrams
        - Industry standards or best practices

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
        - label: I can provide testing and feedback during development
        - label: I can help with documentation
        - label: I can provide domain expertise or requirements clarification