# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# To specify which agents are active by default when --agents is not used,
# uncomment and populate the following line. If omitted, all agents are active.
default_agents = ["copilot", "gemini-cli", "claude", "kiro"]

# Enable nested rule loading from nested .ruler directories
# When enabled, ruler will search for and process .ruler directories throughout the project hierarchy
# nested = false

# --- Global MCP Server Configuration ---
[mcp]
# Enable/disable MCP propagation globally (default: true)
enabled = true
# Global merge strategy: 'merge' or 'overwrite' (default: 'merge')
merge_strategy = "merge"

# --- Global .gitignore Configuration ---
[gitignore]
# Enable/disable automatic .gitignore updates (default: true)
enabled = false

# --- MCP Server Definitions ---
[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", ".", "../terraform-external-context"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.aws-documentation]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]

# --- Agent-Specific Configurations ---
[agents.copilot]
enabled = true

[agents.gemini-cli]
enabled = true

[agents.claude]
enabled = true

[agents.kiro]
enabled = true

[agents.amazonqcli]
enabled = false

[agents.aider]
enabled = false
output_path_instructions = "AGENTS.md"
output_path_config = ".aider.conf.yml"

# OpenAI Codex CLI agent and MCP config
[agents.codex]
enabled = false
output_path = "AGENTS.md"
output_path_config = ".codex/config.toml"

# Agent-specific MCP configuration for Codex CLI
[agents.codex.mcp]
enabled = false
merge_strategy = "merge"

[agents.firebase]
enabled = false
output_path = ".idx/airules.md"

[agents.jules]
enabled = false

[agents.junie]
enabled = false
output_path = ".junie/guidelines.md"

# Agent-specific MCP configuration
[agents.cursor.mcp]
enabled = false
merge_strategy = "merge"

[agents.windsurf]
enabled = false

[agents.kilocode]
enabled = false
output_path = ".kilocode/rules/ruler_kilocode_instructions.md"

[agents.warp]
enabled = false
output_path = "WARP.md"
